import React from 'react';
import './PrivacyPolicy.css';

const PrivacyPolicy = () => (
  <div className="privacy-root">
    <div className="privacy-content">
      <h1 className="privacy-title">PRIVACY POLICY</h1>
      <div className="privacy-updated">Last updated: May 24, 2025</div>
      <p className="privacy-desc">
        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
      </p>
      <p className="privacy-desc">
        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank" rel="noopener noreferrer">Privacy Policy Generator</a>.
      </p>
      <section className="Interpretation-Definitions-section">
        <h2 className="Interpretation-Definitions-title">Interpretation and Definitions</h2>
        <h3 className="Interpretation-Definitions-subtitle">Interpretation</h3>
        <p className="Interpretation-Definitions-desc">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
        <h3 className="Interpretation-Definitions-subtitle">Definitions</h3>
        <p className="Interpretation-Definitions-desc">For the purposes of this Privacy Policy:</p>
        <ul className="Interpretation-Definitions-list">
          <li><b>Account</b> means a unique account created for You to access our Service or parts of our Service.</li>
          <li><b>Affiliate</b> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
          <li><b>Company</b> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Insight Genesis, 60 Paya Lebar Road.</li>
          <li><b>Cookies</b> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of your browsing history on that website among its many uses.</li>
          <li><b>Country</b> refers to: Singapore</li>
          <li><b>Device</b> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
          <li><b>Personal Data</b> is any information that relates to an identified or identifiable individual.</li>
          <li><b>Service</b> refers to the Website.</li>
          <li><b>Service Provider</b> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
          <li><b>Third-party Social Media Service</b> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
          <li><b>Usage Data</b> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
          <li><b>Website</b> refers to <a href="https://insightgenesis.ai/" target="_blank" rel="noopener noreferrer">https://insightgenesis.ai/</a>, accessible from <a href="https://insightgenesis.ai/" target="_blank" rel="noopener noreferrer">https://insightgenesis.ai/</a></li>
          <li><b>You</b> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>
      </section>      
      <section className="Collect-data-section">
        <h2 className="Collect-data-title">Collecting and Using Your Personal Data</h2>
        <h3 className="Collect-data-subtitle">Types of Data Collected</h3>
        <h4 className="Collect-data-subsubtitle">Personal Data</h4>
        <p className="Collect-data-desc">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
        <ul className="Collect-data-list"></ul>
      </section>
    </div>
  </div>
);

export default PrivacyPolicy; 