const COUNTRY_CODES = [
  { name: "Andorra", code: "AD", emoji: "🇦🇩", dial_code: "+376" },
  { name: "United Arab Emirates", code: "AE", emoji: "🇦🇪", dial_code: "+971" },
  { name: "Afghanistan", code: "AF", emoji: "🇦🇫", dial_code: "+93" },
  { name: "Antigua & Barbuda", code: "AG", emoji: "🇦🇬", dial_code: "+1268" },
  { name: "Anguilla", code: "AI", emoji: "🇦🇮", dial_code: "+1264" },
  { name: "Albania", code: "AL", emoji: "🇦🇱", dial_code: "+355" },
  { name: "Armenia", code: "AM", emoji: "🇦🇲", dial_code: "+374" },
  { name: "Angola", code: "AO", emoji: "🇦🇴", dial_code: "+244" },
  { name: "Antarctica", code: "AQ", emoji: "🇦🇶", dial_code: "+672" },
  { name: "Argentina", code: "AR", emoji: "🇦🇷", dial_code: "+54" },
  { name: "American Samoa", code: "AS", emoji: "🇦🇸", dial_code: "+1684" },
  { name: "Austria", code: "AT", emoji: "🇦🇹", dial_code: "+43" },
  { name: "Australia", code: "AU", emoji: "🇦🇺", dial_code: "+61" },
  { name: "Aruba", code: "AW", emoji: "🇦🇼", dial_code: "+297" },
  { name: "Åland Islands", code: "AX", emoji: "🇦🇽", dial_code: "+358" },
  { name: "Azerbaijan", code: "AZ", emoji: "🇦🇿", dial_code: "+994" },
  { name: "Bosnia & Herzegovina", code: "BA", emoji: "🇧🇦", dial_code: "+387" },
  { name: "Barbados", code: "BB", emoji: "🇧🇧", dial_code: "+1246" },
  { name: "Bangladesh", code: "BD", emoji: "🇧🇩", dial_code: "+880" },
  { name: "Belgium", code: "BE", emoji: "🇧🇪", dial_code: "+32" },
  { name: "Burkina Faso", code: "BF", emoji: "🇧🇫", dial_code: "+226" },
  { name: "Bulgaria", code: "BG", emoji: "🇧🇬", dial_code: "+359" },
  { name: "Bahrain", code: "BH", emoji: "🇧🇭", dial_code: "+973" },
  { name: "Burundi", code: "BI", emoji: "🇧🇮", dial_code: "+257" },
  { name: "Benin", code: "BJ", emoji: "🇧🇯", dial_code: "+229" },
  { name: "St. Barthélemy", code: "BL", emoji: "🇧🇱", dial_code: "+590" },
  { name: "Bermuda", code: "BM", emoji: "🇧🇲", dial_code: "+1441" },
  { name: "Brunei", code: "BN", emoji: "🇧🇳", dial_code: "+673" },
  { name: "Bolivia", code: "BO", emoji: "🇧🇴", dial_code: "+591" },
  { name: "Brazil", code: "BR", emoji: "🇧🇷", dial_code: "+55" },
  { name: "Bahamas", code: "BS", emoji: "🇧🇸", dial_code: "+1242" },
  { name: "Bhutan", code: "BT", emoji: "🇧🇹", dial_code: "+975" },
  { name: "Botswana", code: "BW", emoji: "🇧🇼", dial_code: "+267" },
  { name: "Belarus", code: "BY", emoji: "🇧🇾", dial_code: "+375" },
  { name: "Belize", code: "BZ", emoji: "🇧🇿", dial_code: "+501" },
  { name: "Canada", code: "CA", emoji: "🇨🇦", dial_code: "+1" },
  // ... (các nước khác, mỗi object 1 dòng)
];

export default COUNTRY_CODES; 